# Use the official MySQL 8.0 image
FROM mysql:8.0

# Set the root password (change as needed)
ENV MYSQL_ROOT_PASSWORD=root

# Set the default database name (change as needed)
ENV MYSQL_DATABASE=crud

# Expose MySQL default port
EXPOSE 3306
